server:
  port: 8000
spring:
  application:
    name: api-gateway-service
  profiles:
    group:
      "default": "dev"
  config:
    import: secret.yml
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/oauth2/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/login/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
            - AuthorizationParsingFilter

        - id : town-service
          uri: lb://TOWN-SERVICE
          predicates:
            - Path=/town-service/**
          filters:
            - RewritePath=/town-service/(?<segment>.*), /$\{segment}
            - AuthorizationParsingFilter
        - id : used-item-service
          uri: lb://USED-ITEM-SERVICE
          predicates:
            - Path=/used-item-service/**
          filters:
            - RewritePath=/used-item-service/(?<segment>.*), /$\{segment}
            - AuthorizationParsingFilter
            - TownTokenParsingFilter
        - id: block-service
          uri: lb://BLOCK-SERVICE
          predicates:
            - Path=/block-service/**
          filters:
            - RewritePath=/block-service/(?<segment>.*), /$\{segment}
            - AuthorizationParsingFilter
        - id: chat-api
          uri: lb://CHAT-API
          predicates:
            - Path=/chat-api/**
          filters:
            - RewritePath=/chat-api/(?<segment>.*), /$\{segment}
            - AuthorizationParsingFilter
        - id: chat-message
          uri: lb://chat-message
          predicates:
            - Path=/chat-api/token
          filters:
            - RewritePath=/chat-api/(?<segment>.*), /$\{segment}
            - AuthorizationParsingFilter

        - id: chat-message
          uri: lb:ws//chat-message
          predicates:
            - Path=/chat-api/**
          filters:
            - RewritePath=/chat-api/(?<segment>.*), /$\{segment}
        - id: chat-status-management
          uri: lb://chat-status-management
          predicates:
            - Path=/chat-status-management/**
          filters:
            - RewritePath=/chat-status-management/(?<segment>.*), /$\{segment}
